#!/usr/bin/env python3
"""Refresh inventory/domains/index.yaml from a registrar CSV export.

Usage:
    python3 scripts/sync-domains.py registrar-export.csv

Expects CSV header: domain,registrar,expiry,nameservers,purpose,status
nameservers = semicolon-separated list.
"""
import csv
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "inventory" / "domains" / "index.yaml"

def dns_provider_for(ns: list[str]) -> str:
    joined = " ".join(ns).lower()
    if "cloudflare" in joined:
        return "cloudflare"
    if "ns.ternis.net" in joined:
        return "self-hosted"
    return "other"


def main(path: str) -> None:
    rows = []
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            ns = [x.strip() for x in (r.get("nameservers") or "").replace(",", ";").split(";") if x.strip()]
            rows.append({
                "name": r["domain"].strip(),
                "registrar": r.get("registrar", "").strip(),
                "expiry": r.get("expiry", "").strip(),
                "ns_set": ns,
                "dns_provider": r.get("dns_provider", "").strip() or dns_provider_for(ns),
                "purpose": r.get("purpose", "parked").strip() or "parked",
                "status": r.get("status", "active").strip() or "active",
            })
    rows.sort(key=lambda d: d["name"])
    with open(OUT, "w") as f:
        f.write("version: 1\n# Generated by scripts/sync-domains.py from registrar export. Do not hand-edit.\n")
        f.write("# Schema per entry:\n#   - name: example.com\n#     registrar: <name>\n#     expiry: YYYY-MM-DD\n")
        f.write("#     ns_set: [margot.ns.cloudflare.com, martin.ns.cloudflare.com]  # actual authoritative NS\n")
        f.write("#     dns_provider: cloudflare|self-hosted|other  # derived from ns_set, not assumed\n")
        f.write("#     purpose: production|parked|redirect|infra-test\n#     status: active|expired|transfer\n")
        f.write("domains:\n")
        if not rows:
            f.write("  []\n")
        for d in rows:
            f.write(f"  - name: {d['name']}\n")
            f.write(f"    registrar: {d['registrar']}\n")
            f.write(f"    expiry: {d['expiry']}\n")
            f.write(f"    ns_set: [{', '.join(d['ns_set'])}]\n")
            f.write(f"    dns_provider: {d['dns_provider']}\n")
            f.write(f"    purpose: {d['purpose']}\n")
            f.write(f"    status: {d['status']}\n")
    print(f"wrote {len(rows)} domains to {OUT}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
